apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1-dev
  namespace: argo
spec:
  project: default
  source:
    repoURL: 'git@github.com:CompuZest/infra-deploy-terraform-config.git'
    path: 1/dev
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
