image:
  name: zlifecycle-web-bff
  tag: latest
  repository:
# rename zcustomer with the client name
domain: zcustomer.zlifecycle.com
company: !!!CompanyName!!!
ingressPaths:
  - "/auth"
  - "/cd"
  - "/wf"
  - "/authorize"
  - "/costing"
  - "/reconciliation"
  - "/secrets"
  - "/terraform"
  - "/terraform-external"
  - "/state"
  - "/company"
  - "/registration"
  - "/error-api"
  - "/events"
protocol:
auth0:
  baseUrl:
  clientId:
  issuerBaseUrl:
  secret:
argocd:
  openIdClientId:
  openIdClientSecret:
  urlWithProtocol: http://argocd-server.argocd.svc.cluster.local
  openIdIssuerUrl: http://argocd-server.argocd.svc.cluster.local/api/dex
argoWorkflowApiUrl: http://argo-workflow-server.argocd.svc.cluster.local:2746
zlifecycleApiUrl: http://zlifecycle-api.zlifecycle-ui.svc.cluster.local
zlifecycleStateManagerUrl: http://zlifecycle-state-manager.zlifecycle-il-operator-system.svc.cluster.local
zlifecycleEventApiUrl: http://event-service.zbank-system.svc.cluster.local
