apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-admin
  namespace: {{.Values.namespace}}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{.Values.namespace}}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
