apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-terraform
  namespace: argo
spec:
  entrypoint: run
  templates:
    - name: run
      inputs:
        parameters:
          - name: module_source
          - name: module_source_path
          - name: is_apply
          - name: lock_state
            value: true
          - name: customer_id
          - name: env_name
        artifacts:
          - name: terraform-config
            path: "/home"
            git:
              repo: '"{{"{{"}}inputs.parameters.module_source{{"}}"}}"'
              sshPrivateKeySecret:
                name: github-ssh-key
                key: id_rsa
              insecureIgnoreHostKey: true
      serviceAccountName: argo
      script:
        imagePullPolicy: Always
        image: shahadarsh/terraform:latest
        cmd:
          - sh
        source: |
          cd /home/"{{"{{"}}inputs.parameters.module_source_path{{"}}"}}"
          mkdir ~/.ssh
          cat /root/ssh_secret/id_rsa >> ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

          mkdir ~/.aws
          cat <<EOT >> ~/.aws/credentials
          [default]
          aws_access_key_id = ${CUSTOMER_AWS_ACCESS_KEY_ID}
          aws_secret_access_key = ${CUSTOMER_AWS_SECRET_ACCESS_KEY}
          [compuzest-shared]
          aws_access_key_id = ${SHARED_AWS_ACCESS_KEY_ID}
          aws_secret_access_key = ${SHARED_AWS_SECRET_ACCESS_KEY}
          EOT

          customer_id="{{"{{"}}inputs.parameters.customer_id{{"}}"}}"
          env_name="{{"{{"}}inputs.parameters.env_name{{"}}"}}"
          lock_state="{{"{{"}}inputs.parameters.lock_state{{"}}"}}"
          cust_id_env_name=$customer_id-$env_name

          terraform init
          terraform workspace new $cust_id_env_name
          terraform workspace select $cust_id_env_name
          terraform init

          if [ "{{"{{"}}inputs.parameters.is_apply{{"}}"}}" -eq 0 ]
          then
            terraform plan -lock=$lock_state -detailed-exitcode -var-file tfvars/$customer_id/$env_name.tfvars
            result=$?
            echo -n $result > /tmp/plan_code.txt

            if [ $result -eq 2 ]
            then
              curl -d '{"channel":"slack-notification","message":"Networking Terraform is Out of Sync. Please approve Sync."}' -H "Content-Type: application/json" -X POST http://webhook-eventsource-svc.argo.svc.cluster.local:12000/terraform-diff
            fi
          else
            terraform apply -var-file tfvars/$customer_id/$env_name.tfvars -auto-approve
            echo -n 0 > /tmp/plan_code.txt
            curl -d '{"channel":"slack-notification","message":"Networking Terraform is back in Sync now."}' -H "Content-Type: application/json" -X POST http://webhook-eventsource-svc.argo.svc.cluster.local:12000/terraform-diff
          fi
        env:
          - name: CUSTOMER_AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: aws_access_key_id
          - name: CUSTOMER_AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: aws_secret_access_key
          - name: SHARED_AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: shared-aws-creds
                key: aws_access_key_id
          - name: SHARED_AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: shared-aws-creds
                key: aws_secret_access_key
        volumeMounts:
          - name: github-ssh-key-mount
            mountPath: "/root/ssh_secret"
            readOnly: false
      outputs:
        parameters:
          - name: planCode
            valueFrom:
              path: /tmp/plan_code.txt
            globalName: plan-code
