---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1-dev-terraform-config-networking
  namespace: argo
  annotations:
    recipients.argocd-notifications.argoproj.io: slack:random
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: default
    server: "https://192.168.1.155:58956"
  source:
    repoURL: git@github.com:CompuZest/helm-charts.git
    path: charts/terraform-config
    targetRevision: HEAD
    helm:
      values: |
        customer_id: "1"
        env_name: "dev"
        name: "networking"
        module:
          source: "git@github.com:CompuZest/infra-deploy-networking.git"
          path: aws-vpc
        variables:
          - name: cidr
            value: "10.1.0.0/16"
          - name: azs
            value: '["us-east-1a", "us-east-1b", "us-east-1c"]'
          - name: private_subnets
            value: '["10.1.0.0/19", "10.1.64.0/19", "10.1.128.0/19"]'
          - name: public_subnets
            value: '["10.1.48.0/20", "10.1.112.0/20", "10.1.176.0/20"]'
        outputs: ""
