---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1-dev-terraform-config-platform-eks
  namespace: argo
  annotations:
    recipients.argocd-notifications.argoproj.io: slack:random
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: default
    server: "https://192.168.1.155:58956"
  source:
    repoURL: git@github.com:CompuZest/helm-charts.git
    path: charts/terraform-config
    targetRevision: HEAD
    helm:
      values: |
        customer_id: "1"
        env_name: "dev"
        name: "platform-eks"
        module:
          source: "git@github.com:CompuZest/infra-deploy-platform.git"
          path: aws-eks
        variables:
          - name: cidr
            value: "10.1.0.0/16"
        outputs: ""
