site_name: zLifecycle - Environment Managment Made Easy
theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
markdown_extensions:
- codehilite
- admonition
- toc:
    permalink: true
nav:
- Overview: index.md
- concepts/index.md
- getting_started/index.md
- Settings:
  - settings/aws-credentials.md
  - settings/secrets.md
- Define:
  - define/define-environment.md
  - define/field-reference.md
- Provision:
  - steps.md
- Reconcile:
  - steps.md
- Teardown:
  - steps.md
- Team:
  - team/index.md
  - team/onboard.md
- Dashboard:
  - steps.md
