site_name: zLifecycle - Environment Managment Made Easy
site_url: https://docs.zlifecycle.com/
theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
markdown_extensions:
- codehilite
- admonition
- toc:
    permalink: true
nav:
- Overview: index.md
- Core Concepts:
  - concepts/concepts.md
- Getting Started:
  - getting_started/index.md
  - getting_started/onboard_team.md
- Settings:
  - settings/aws_credentials.md
  - settings/secrets.md
  - settings/zlifecycle_app_installation.md
- Define:
  - define/define_environment.md
  - define/field_reference.md
  - define/examples.md
- Policies:
  - policies/approval.md
  - policies/manual_approval.md
  - policies/destroy.md
  - policies/selective_reconcile.md
  - policies/manual.md
  - policies/auto.md
  - policies/teardown.md
  - policies/cost_estimates.md
- component_details_view.md
- errors.md
- support/supported_platforms.md

