site_name: zLifecycle
theme: material
markdown_extensions:
- codehilite
- admonition
- toc:
    permalink: true
nav:
- Overview: index.md
- concepts/index.md
- getting_started/index.md
- Team:
  - team/index.md
  - team/onboard.md
- Define:
  - define/define-environment.md
  - define/field-reference.md
- Provision:
  - steps.md
- Reconcile:
  - steps.md
- Teardown:
  - steps.md
- Dashboard:
  - steps.md
