site_name: zLifecycle
theme: readthedocs
nav:
  - Overview: index.md
  - Core Concepts: core-concepts.md
  - Getting Started:
    - Setting up: setup.md
    - Onboard a Team: team/onboarding.md
    - Provision your First Environment: provision/first-environment.md
    - Teardown your First Environment: teardown/first-environment.md
  - Define:
    - Define Environment: define/define-environment.md
    - Field Reference: define/field-reference.md
  - Provision:
    - Steps: steps.md
  - Reconcile:
    - Steps: steps.md
  - Teardown:
    - Steps: steps.md
  - Dashboards:
    - Steps: steps.md
