image:
  name: zlifecycle-api
  tag: latest
  repository:
replicas: 1
database:
  host:
  username:
  password:
  name:
  port:
awsCredentials:
  accessKeyId:
  secretAccessKey:
  region:
argowf:
  url:
  namespace:
org:
  argoWf:
    url: ""
ckEnvironment:
namespace: zlifecycle-system
resources:
  requests:
    cpu: 200m
    memory: 256Mi
