apiVersion: v1
kind: Service
metadata:
  name: zlifecycle-web
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 80
  selector:
    app: zlifecycle-web
