---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-stable-compuzest-com-v1-environment
  failurePolicy: Fail
  name: venvironment.kb.io
  rules:
  - apiGroups:
    - stable.compuzest.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - environments
  sideEffects: None
