apiVersion: apps/v1
kind: Deployment
metadata:
  name: zlifecycle-il-operator-controller-manager
  labels:
    {{- include "core.labels" . | indent 4 }}
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        {{- include "core.labels" . | indent 8 }}
        control-plane: controller-manager
    spec:
      containers:
      - name: manager
        command:
          - /manager
        args:
          - --enable-leader-election
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 9443
            name: webhook-server
            protocol: TCP
        volumeMounts:
          - mountPath: /tmp/k8s-webhook-server/serving-certs
            name: cert
            readOnly: true
        env:
          - name: GITHUB_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-auth-token
                key: token
          - name: ZLIFECYCLE_OPERATOR_NAMESPACE
            value: {{ .Release.Namespace }}
          {{- include "core.deployment.container-env" . | indent 10 }}
        envFrom:
          - configMapRef:
              name: company-config
          - secretRef:
              name: argocd-creds
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert
      terminationGracePeriodSeconds: 10
