---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ .Values.company.config.name }}-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - stable.cloudknit.io
  resources:
  - companies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stable.cloudknit.io
  resources:
  - companies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - stable.cloudknit.io
  resources:
  - environments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stable.cloudknit.io
  resources:
  - environments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - stable.cloudknit.io
  resources:
  - teams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stable.cloudknit.io
  resources:
  - teams/status
  verbs:
  - get
  - patch
  - update
