nameOverride: ""
fullnameOverride: ""

image:
  repository: 413422438110.dkr.ecr.us-east-1.amazonaws.com/zlifecycle-il-operator
  tag: latest
  pullPolicy: Always
  pullSecret: ""

deployment:
  replicas: 1

env:
  ARGOCD_SERVER_URL: "argocd-server"
  ARGOCD_WEBHOOK_URL: "https://xxx.zlifecycle.com/api/webhook"
  GITHUB_ZLIFECYCLE_OWNER: zlifecycle-il
  GITHUB_WEBHOOK_SECRET: "!!!CHANGEME!!!"
  GITHUB_ORG: "!!!CHANGEME!!!"
  ZLIFECYCLE_MASTER_SSH: zlifecycle-operator-ssh
  ENABLE_NEW_RELIC: "false"
  NEW_RELIC_API_KEY: ""
  SLACK_WEBHOOK_URL: ""
  TF_IL_REPO_URL: ""
  TF_IL_REPO_NAME: ""

resources:
  limits:
    cpu: 400m
    memory: 500Mi
  requests:
    cpu: 200m
    memory: 250Mi

companyConfigMap:
  enabled: true
  data:
    companyName: "zCustomer"
    adminEmail: "admin@compuzest.com"
    teamsConfigPath: "teams"
    configRepo: "git@github.com:zbank-tech/zcustomer-config.git"
    configRepoName: "zcustomer-config"
    ilRepo: "git@github.com:CompuZest/zcustomer-il.git"
    ilRepoSourceOwner: "zlifecycle-il"
    ilRepoName: "zcustomer-il"
    helmChartsRepo: "git@github.com:CompuZest/helm-charts.git"
