name: Build Stable zLifecycle
on:
  workflow_dispatch:

jobs:
  build-zlifecycle:
    name: Build docker image for terraform provisioner
    runs-on: ubuntu-20.04
    steps:
      - name: Invoke build stable zlifecycle terraform image
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Manual Docker Build
          inputs: '{ "image_tag": "stable" }'
          token: ${{ secrets.COMPUZEST_TOKEN }}

      - name: Invoke build stable zlifecycle-il-operator
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Manual Build Stable Workflow
          repo: CompuZest/zlifecycle-il-operator
          token: ${{ secrets.COMPUZEST_TOKEN }}

      - name: Invoke build stable zlifecycle-web
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Manual Build Stable Workflow
          repo: CompuZest/zlifecycle-web
          token: ${{ secrets.COMPUZEST_TOKEN }}

      - name: Invoke build stable zlifecycle-web-bff
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build stable zLifecycle-web-bff
          repo: CompuZest/zlifecycle-web-bff
          token: ${{ secrets.COMPUZEST_TOKEN }}

      - name: Invoke build stable zlifecycle-web-bff
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Manual Build Stable Workflow
          repo: CompuZest/zlifecycle-api
          token: ${{ secrets.COMPUZEST_TOKEN }}
