apiVersion: apps/v1
kind: Deployment
metadata:
  name: zlifecycle-il-operator-controller-manager
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: 413422438110.dkr.ecr.us-east-1.amazonaws.com/zlifecycle-il-operator:latest
        imagePullPolicy: Always
        name: manager
        env:
          - name: GITHUB_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-auth-token
                key: token
          - name: K8s_API_URL
            valueFrom:
              secretKeyRef:
                name: k8s-api
                key: url
        envFrom:
          - configMapRef:
              name: company-config
          - secretRef:
              name: argocd-creds
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
