// Code generated by MockGen. DO NOT EDIT.
// Source: ./file.go

// Package mocks is a generated GoMock package.
package mocks

import (
	os "os"
	reflect "reflect"
	template "text/template"

	v1 "github.com/compuzest/zlifecycle-il-operator/api/v1"
	gomock "github.com/golang/mock/gomock"
)

// MockFSAPI is a mock of FSAPI interface.
type MockFSAPI struct {
	ctrl     *gomock.Controller
	recorder *MockFSAPIMockRecorder
}

// MockFSAPIMockRecorder is the mock recorder for MockFSAPI.
type MockFSAPIMockRecorder struct {
	mock *MockFSAPI
}

// NewMockFSAPI creates a new mock instance.
func NewMockFSAPI(ctrl *gomock.Controller) *MockFSAPI {
	mock := &MockFSAPI{ctrl: ctrl}
	mock.recorder = &MockFSAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFSAPI) EXPECT() *MockFSAPIMockRecorder {
	return m.recorder
}

// CreateEmptyDirectory mocks base method.
func (m *MockFSAPI) CreateEmptyDirectory(folderName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmptyDirectory", folderName)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEmptyDirectory indicates an expected call of CreateEmptyDirectory.
func (mr *MockFSAPIMockRecorder) CreateEmptyDirectory(folderName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmptyDirectory", reflect.TypeOf((*MockFSAPI)(nil).CreateEmptyDirectory), folderName)
}

// NewFile mocks base method.
func (m *MockFSAPI) NewFile(folderName, fileName string) (*os.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewFile", folderName, fileName)
	ret0, _ := ret[0].(*os.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewFile indicates an expected call of NewFile.
func (mr *MockFSAPIMockRecorder) NewFile(folderName, fileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewFile", reflect.TypeOf((*MockFSAPI)(nil).NewFile), folderName, fileName)
}

// RemoveAll mocks base method.
func (m *MockFSAPI) RemoveAll(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAll", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAll indicates an expected call of RemoveAll.
func (mr *MockFSAPIMockRecorder) RemoveAll(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAll", reflect.TypeOf((*MockFSAPI)(nil).RemoveAll), path)
}

// SaveFileFromByteArray mocks base method.
func (m *MockFSAPI) SaveFileFromByteArray(input []byte, folderName, fileName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFileFromByteArray", input, folderName, fileName)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFileFromByteArray indicates an expected call of SaveFileFromByteArray.
func (mr *MockFSAPIMockRecorder) SaveFileFromByteArray(input, folderName, fileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFileFromByteArray", reflect.TypeOf((*MockFSAPI)(nil).SaveFileFromByteArray), input, folderName, fileName)
}

// SaveFileFromString mocks base method.
func (m *MockFSAPI) SaveFileFromString(input, folderName, fileName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFileFromString", input, folderName, fileName)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFileFromString indicates an expected call of SaveFileFromString.
func (mr *MockFSAPIMockRecorder) SaveFileFromString(input, folderName, fileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFileFromString", reflect.TypeOf((*MockFSAPI)(nil).SaveFileFromString), input, folderName, fileName)
}

// SaveFileFromTemplate mocks base method.
func (m *MockFSAPI) SaveFileFromTemplate(t *template.Template, vars interface{}, folderName, fileName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFileFromTemplate", t, vars, folderName, fileName)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFileFromTemplate indicates an expected call of SaveFileFromTemplate.
func (mr *MockFSAPIMockRecorder) SaveFileFromTemplate(t, vars, folderName, fileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFileFromTemplate", reflect.TypeOf((*MockFSAPI)(nil).SaveFileFromTemplate), t, vars, folderName, fileName)
}

// SaveVarsToFile mocks base method.
func (m *MockFSAPI) SaveVarsToFile(variables []*v1.Variable, folderName, fileName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveVarsToFile", variables, folderName, fileName)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveVarsToFile indicates an expected call of SaveVarsToFile.
func (mr *MockFSAPIMockRecorder) SaveVarsToFile(variables, folderName, fileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveVarsToFile", reflect.TypeOf((*MockFSAPI)(nil).SaveVarsToFile), variables, folderName, fileName)
}

// SaveYamlFile mocks base method.
func (m *MockFSAPI) SaveYamlFile(obj interface{}, folderName, fileName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveYamlFile", obj, folderName, fileName)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveYamlFile indicates an expected call of SaveYamlFile.
func (mr *MockFSAPIMockRecorder) SaveYamlFile(obj, folderName, fileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveYamlFile", reflect.TypeOf((*MockFSAPI)(nil).SaveYamlFile), obj, folderName, fileName)
}
