export const ENVIRONMENT_VARIABLES = {
    REACT_APP_CUSTOMER_NAME: `${process.env.REACT_APP_CUSTOMER_NAME}`,
    REACT_APP_BASE_URL: `${process.env.REACT_APP_BASE_URL}`,
    REACT_APP_CAL_LINK: `${process.env.REACT_APP_CAL_LINK}`
}