// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/compuzest/zlifecycle-il-operator/controllers/argocd (interfaces: Api)

// Package argocd is a generated GoMock package.
package argocd

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// mockApi is a mock of Api interface.
type mockApi struct {
	ctrl     *gomock.Controller
	recorder *MockArgocdAPIMockRecorder
}

// MockArgocdAPIMockRecorder is the mock recorder for mockApi.
type MockArgocdAPIMockRecorder struct {
	mock *mockApi
}

// NewMockApi creates a new mock instance.
func NewMockApi(ctrl *gomock.Controller) *mockApi {
	mock := &mockApi{ctrl: ctrl}
	mock.recorder = &MockArgocdAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *mockApi) EXPECT() *MockArgocdAPIMockRecorder {
	return m.recorder
}

// CreateRepository mocks base method.
func (m *mockApi) CreateRepository(arg0 CreateRepoBody, arg1 string) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRepository", arg0, arg1)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRepository indicates an expected call of CreateRepository.
func (mr *MockArgocdAPIMockRecorder) CreateRepository(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRepository", reflect.TypeOf((*mockApi)(nil).CreateRepository), arg0, arg1)
}

// GetAuthToken mocks base method.
func (m *mockApi) GetAuthToken() (*GetTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthToken")
	ret0, _ := ret[0].(*GetTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthToken indicates an expected call of GetAuthToken.
func (mr *MockArgocdAPIMockRecorder) GetAuthToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthToken", reflect.TypeOf((*mockApi)(nil).GetAuthToken))
}

// ListRepositories mocks base method.
func (m *mockApi) ListRepositories(arg0 string) (*RepositoryList, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRepositories", arg0)
	ret0, _ := ret[0].(*RepositoryList)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRepositories indicates an expected call of ListRepositories.
func (mr *MockArgocdAPIMockRecorder) ListRepositories(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRepositories", reflect.TypeOf((*mockApi)(nil).ListRepositories), arg0)
}
