apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: dev
  namespace: argo
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
  labels:
    workflows.argoproj.io/completed: 'false'
    terraform/sync: 'true'
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: networking
            template: triggerWorkflowUsingResourceWithArgument
            arguments:
              parameters:
                - name: workflowtemplate
                  value: "terraform-sync-template"
                - name: module_source
                  value: "git@github.com:CompuZest/infra-deploy-networking.git"
                - name: module_source_path
                  value: "aws-vpc"
                - name: env_name
                  value: "dev"
                - name: customer_id
                  value: '"1"'
                - name: name
                  value: "networking"
        - - name: platform-eks
            template: triggerWorkflowUsingResourceWithArgument
            arguments:
              parameters:
                - name: workflowtemplate
                  value: "terraform-sync-template"
                - name: module_source
                  value: "git@github.com:CompuZest/infra-deploy-platform.git"
                - name: module_source_path
                  value: aws-eks
                - name: env_name
                  value: "dev"
                - name: customer_id
                  value: '"1"'
                - name: name
                  value: "platform-eks"

    - name: triggerWorkflowUsingResourceWithArgument
      inputs:
        parameters:
          - name: workflowtemplate
          - name: module_source
          - name: module_source_path
          - name: customer_id
          - name: env_name
          - name: name
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: {{inputs.parameters.name}}
            namespace: argo
            labels:
              terraform/sync: 'true'
          spec:
            arguments:
              parameters:
              - name: module_source
                value: {{inputs.parameters.module_source}}
              - name: module_source_path
                value: {{inputs.parameters.module_source_path}}
              - name: customer_id
                value: {{inputs.parameters.customer_id}}
              - name: env_name
                value: {{inputs.parameters.env_name}}
              - name: name
                value: {{inputs.parameters.name}}
            workflowTemplateRef:
              name: {{inputs.parameters.workflowtemplate}}
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
