# Copyright (C) 2020 CompuZest, Inc. - All Rights Reserved
#
# Unauthorized copying of this file, via any medium, is strictly prohibited
# Proprietary and confidential
#
# NOTICE: All information contained herein is, and remains the property of
# CompuZest, Inc. The intellectual and technical concepts contained herein are
# proprietary to CompuZest, Inc. and are protected by trade secret or copyright
# law. Dissemination of this information or reproduction of this material is
# strictly forbidden unless prior written permission is obtained from CompuZest, Inc.
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: "{{ .Values.team_name}}-{{ .Values.env_name}}-{{ .Values.config_name}}-control-loop"
  namespace: {{.Values.namespace}}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    zlifecycle.com/model: 'control-loop'
spec:
  schedule: "{{.Values.cron_schedule}}"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowMetadata:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
  workflowSpec:
    entrypoint: control-loop
    podGC:
      strategy: OnPodSuccess
    ttlStrategy:
      secondsAfterSuccess: 5
    volumes:
      - name: github-ssh-key-mount
        secret:
          secretName: github-ssh-key
          defaultMode: 384
    templates:
      - name: control-loop
        steps:
          - - name: plan
              templateRef:
                name: terraform-run-template
                template: run
              arguments:
                parameters:
                  - name: team_name
                    value: "{{ .Values.team_name }}"
                  - name: env_name
                    value: "{{ .Values.env_name }}"
                  - name: config_name
                    value: "{{ .Values.config_name }}"
                  - name: module_source
                    value: "{{ .Values.module.source }}"
                  - name: module_source_path
                    value: "{{ .Values.module.path }}"
                  - name: variables_file_source
                    value: "{{ .Values.variables_file.source }}"
                  - name: variables_file_path
                    value: "{{ .Values.variables_file.path }}"
                  - name: is_apply
                    value: "0"
                  - name: lock_state
                    value: "false"
