---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: terraform-config-networking-
  namespace: argo
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
  labels:
    workflows.argoproj.io/completed: 'false'
spec:
  entrypoint: update
  volumes:
    - name: github-ssh-key-mount
      secret:
        secretName: github-ssh-key
        defaultMode: 384
  arguments:
    parameters:
      - name: module_source
        value: "{{ .Values.module.source }}"
  templates:
    - name: update
      steps:
        - - name: plan
            templateRef:
              name: workflow-template-terraform-plan
              template: plan
            arguments:
              parameters:
                - name: module_source
                  value: "{{ .Values.module.source }}"
                - name: is_apply
                  value: 0
        - - name: approve
            template: approve
            when: "{{` {{steps.plan.outputs.parameters.planCode}} == 2 `}}"
        - - name: apply
            templateRef:
              name: workflow-template-terraform-plan
              template: plan
            arguments:
              parameters:
                - name: module_source
                  value: "{{ .Values.module.source }}"
                - name: is_apply
                  value: 1
            when: "{{` {{steps.plan.outputs.parameters.planCode}} == 2 `}}"


    - name: approve
      suspend: {}

    - name: apply
      inputs:
        artifacts:
          - name: terraform-config
            path: /home
            git:
              repo: git@github.com:CompuZest/infra-deploy-networking.git
              sshPrivateKeySecret:
                name: github-ssh-key
                key: id_rsa
              insecureIgnoreHostKey: true
      serviceAccountName: argo
      script:
        imagePullPolicy: "Always"
        image: shahadarsh/terraform:latest
        cmd: ["sh"]
        source: |
          cd /home/aws-vpc
          mkdir ~/.ssh
          cat /root/ssh_secret/id_rsa >> ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

          mkdir ~/.aws
          cat <<EOT >> ~/.aws/credentials
          [default]
          aws_access_key_id = ${CUSTOMER_AWS_ACCESS_KEY_ID}
          aws_secret_access_key = ${CUSTOMER_AWS_SECRET_ACCESS_KEY}
          [compuzest-shared]
          aws_access_key_id = ${SHARED_AWS_ACCESS_KEY_ID}
          aws_secret_access_key = ${SHARED_AWS_SECRET_ACCESS_KEY}
          EOT

          terraform init
          terraform workspace new 1-dev
          terraform workspace select 1-dev
          terraform init
          terraform apply -var-file tfvars/1/dev.tfvars -auto-approve
          curl -d '{"channel":"slack-notification","message":"Networking Terraform is  back in Sync now."}' -H "Content-Type: application/json" -X POST http://webhook-eventsource-svc.argo.svc.cluster.local:12000/terraform-diff
        env:
          - name: CUSTOMER_AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: aws_access_key_id
          - name: CUSTOMER_AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: aws_secret_access_key
          - name: SHARED_AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: shared-aws-creds
                key: aws_access_key_id
          - name: SHARED_AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: shared-aws-creds
                key: aws_secret_access_key
        volumeMounts:
          - name: github-ssh-key-mount
            mountPath: "/root/ssh_secret"
            readOnly: false
