---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: "{{ .Values.name}}-control-loop"
  namespace: argo
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    terraform/control-loop: 'true'
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowMetadata:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
  workflowSpec:
    entrypoint: control-loop
    volumes:
      - name: github-ssh-key-mount
        secret:
          secretName: github-ssh-key
          defaultMode: 384
    arguments:
      parameters:
        - name: module_source
          value: "{{ .Values.module.source }}"
        - name: module_source_path
          value: "{{ .Values.module.path }}"
        - name: variables_file_source
          value: "{{ .Values.variables_file.source }}"
        - name: variables_file_path
          value: "{{ .Values.variables_file.path }}"
        - name: name
          value: "{{ .Values.name }}"
    templates:
      - name: control-loop
        steps:
          - - name: plan
              templateRef:
                name: workflow-template-terraform
                template: run
              arguments:
                parameters:
                  - name: module_source
                    value: "{{ .Values.module.source }}"
                  - name: module_source_path
                    value: "{{ .Values.module.path }}"
                  - name: variables_file_source
                    value: "{{ .Values.variables_file.source }}"
                  - name: variables_file_path
                    value: "{{ .Values.variables_file.path }}"
                  - name: is_apply
                    value: "0"
                  - name: lock_state
                    value: "false"
                  - name: customer_id
                    value: '"{{ .Values.customer_id }}"'
                  - name: env_name
                    value: "{{ .Values.env_name }}"
                  - name: name
                    value: "{{ .Values.name }}"
