---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: terraform-config-networking-
  namespace: argo
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
  labels:
    workflows.argoproj.io/completed: 'false'
spec:
  entrypoint: update
  volumes:
    - name: github-ssh-key-mount
      secret:
        secretName: github-ssh-key
        defaultMode: 384
  arguments:
    parameters:
      - name: module_source
        value: "{{ .Values.module.source }}"
  templates:
    - name: update
      steps:
        - - name: plan
            templateRef:
              name: workflow-template-terraform-plan
              template: plan
            arguments:
              parameters:
                - name: module_source
                  value: "{{ .Values.module.source }}"
                - name: is_apply
                  value: 0
        - - name: approve
            template: approve
            when: "{{` {{steps.plan.outputs.parameters.planCode}} == 2 `}}"
        - - name: apply
            templateRef:
              name: workflow-template-terraform-plan
              template: plan
            arguments:
              parameters:
                - name: module_source
                  value: "{{ .Values.module.source }}"
                - name: is_apply
                  value: 1
            when: "{{` {{steps.plan.outputs.parameters.planCode}} == 2 `}}"


    - name: approve
      suspend: {}
