# Copyright (C) 2020 CompuZest, Inc. - All Rights Reserved
#
# Unauthorized copying of this file, via any medium, is strictly prohibited
# Proprietary and confidential
#
# NOTICE: All information contained herein is, and remains the property of
# CompuZest, Inc. The intellectual and technical concepts contained herein are
# proprietary to CompuZest, Inc. and are protected by trade secret or copyright
# law. Dissemination of this information or reproduction of this material is
# strictly forbidden unless prior written permission is obtained from CompuZest, Inc.
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-trigger-template
  namespace: argocd
spec:
  entrypoint: run
  podGC:
    strategy: OnWorkflowSuccess
  ttlStrategy:
    secondsAfterSuccess: 600
    secondsAfterCompletion: 600
  templates:
    - name: run
      serviceAccountName: argo
      inputs:
        parameters:
          - name: team_name
          - name: env_name
          - name: config_name
          - name: workflowtemplate
          - name: module_source
          - name: module_source_path
          - name: il_repo
          - name: status
          - name: terraform_il_path
          - name: is_destroy
          - name: reconcile_id
      steps:
        - - name: init-component-audit
            template: audit_sh
            arguments:
              parameters:
                - name: team_name
                  value: '{{ printf "{{inputs.parameters.team_name}}" }}'
                - name: env_name
                  value: '{{ printf "{{inputs.parameters.env_name}}" }}'
                - name: config_name
                  value: '{{ printf "{{inputs.parameters.config_name}}" }}'
                - name: status
                  value: '{{ printf "{{inputs.parameters.status}}" }}'
                - name: config_status
                  value: "Initialising..."
                - name: reconcile_id
                  value: '{{ printf "{{inputs.parameters.reconcile_id}}" }}'
                - name: config_reconcile_id
                  value: 0
        - - name: validate
            template: validate_env_component
            arguments:
              parameters:
                - name: team_name
                  value: '{{ printf "{{inputs.parameters.team_name}}" }}'
                - name: env_name
                  value: '{{ printf "{{inputs.parameters.env_name}}" }}'
                - name: config_name
                  value: '{{ printf "{{inputs.parameters.config_name}}" }}'
        - - name: run
            template: run_env_component
            arguments:
              parameters:
                - name: team_name
                  value: '{{ printf "{{inputs.parameters.team_name}}" }}'
                - name: env_name
                  value: '{{ printf "{{inputs.parameters.env_name}}" }}'
                - name: config_name
                  value: '{{ printf "{{inputs.parameters.config_name}}" }}'
                - name: workflowtemplate
                  value: '{{ printf "{{inputs.parameters.workflowtemplate}}" }}'
                - name: module_source
                  value: '{{ printf "{{inputs.parameters.module_source}}" }}'
                - name: module_source_path
                  value: '{{ printf "{{inputs.parameters.module_source_path}}" }}'
                - name: il_repo
                  value: '{{ printf "{{inputs.parameters.il_repo}}" }}'
                - name: terraform_il_path
                  value: '{{ printf "{{inputs.parameters.terraform_il_path}}" }}'
                - name: is_destroy
                  value: '{{ printf "{{inputs.parameters.is_destroy}}" }}'
                - name: config_reconcile_id
                  value: '{{ printf "{{steps.init-component-audit.outputs.parameters.reconcile_id}}" }}'
                - name: reconcile_id
                  value: '{{ printf "{{inputs.parameters.reconcile_id}}" }}'
            when: '{{ printf "{{steps.validate.outputs.parameters.errorCode}}" }} != 20'
        - - name: end-component-audit
            template: audit_sh
            arguments:
              parameters:
                - name: team_name
                  value: '{{ printf "{{inputs.parameters.team_name}}" }}'
                - name: env_name
                  value: '{{ printf "{{inputs.parameters.env_name}}" }}'
                - name: config_name
                  value: '{{ printf "{{inputs.parameters.config_name}}" }}'
                - name: status
                  value: '{{ printf "{{inputs.parameters.status}}" }}'
                - name: config_status
                  value: "Success"
                - name: reconcile_id
                  value: '{{ printf "{{inputs.parameters.reconcile_id}}" }}'
                - name: config_reconcile_id
                  value: '{{ printf "{{steps.init-component-audit.outputs.parameters.reconcile_id}}" }}'

    - name: validate_env_component
      inputs:
        parameters:
          - name: team_name
          - name: env_name
          - name: config_name
      script:
        imagePullPolicy: Always
        image: 413422438110.dkr.ecr.us-east-1.amazonaws.com/zlifecycle-terraform:latest
        cmd:
          - sh
        source: |
          ./validate_env_component.sh '{{ printf "{{inputs.parameters.team_name}}" }}' '{{ printf "{{inputs.parameters.env_name}}" }}' '{{ printf "{{inputs.parameters.config_name}}" }}'
      volumes:
        - name: tmp
          emptyDir: {}
      outputs:
        parameters:
          - name: errorCode
            valueFrom:
              path: /tmp/error_code.txt
            globalName: error-code

    - name: run_env_component
      inputs:
        parameters:
          - name: team_name
          - name: env_name
          - name: config_name
          - name: workflowtemplate
          - name: module_source
          - name: module_source_path
          - name: il_repo
          - name: terraform_il_path
          - name: is_destroy
          - name: config_reconcile_id
          - name: reconcile_id
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: '{{ printf "{{inputs.parameters.team_name}}" }}-{{ printf "{{inputs.parameters.env_name}}" }}-{{ printf "{{inputs.parameters.config_name}}" }}'
            namespace: argocd
            labels:
              terraform/sync: 'true'
          spec:
            arguments:
              parameters:
              - name: team_name
                value: '{{ printf "{{inputs.parameters.team_name}}" }}'
              - name: env_name
                value: '{{ printf "{{inputs.parameters.env_name}}" }}'
              - name: config_name
                value: '{{ printf "{{inputs.parameters.config_name}}" }}'
              - name: module_source
                value: '{{ printf "{{inputs.parameters.module_source}}" }}'
              - name: module_source_path
                value: '{{ printf "{{inputs.parameters.module_source_path}}" }}'
              - name: il_repo
                value: '{{ printf "{{inputs.parameters.il_repo}}" }}'
              - name: terraform_il_path
                value: '{{ printf "{{inputs.parameters.terraform_il_path}}" }}'
              - name: is_destroy
                value: '{{ printf "{{inputs.parameters.is_destroy}}" }}'
              - name: reconcile_id
                value: '{{ printf "{{inputs.parameters.reconcile_id}}" }}'
              - name: config_reconcile_id
                value: '{{ printf "{{inputs.parameters.config_reconcile_id}}" }}'
            workflowTemplateRef:
              name: '{{ printf "{{inputs.parameters.workflowtemplate}}" }}'
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)

    - name: audit_sh
      inputs:
        parameters:
          - name: team_name
          - name: env_name
          - name: config_name
          - name: status
          - name: config_status
          - name: reconcile_id
          - name: config_reconcile_id
      script:
        imagePullPolicy: Always
        image: 413422438110.dkr.ecr.us-east-1.amazonaws.com/zlifecycle-terraform:latest
        cmd:
          - sh
        source: |
          ./audit.sh '{{ printf "{{inputs.parameters.team_name}}" }}' '{{ printf "{{inputs.parameters.env_name}}" }}' '{{ printf "{{inputs.parameters.config_name}}" }}' '{{ printf "{{inputs.parameters.status}}" }}' '{{ printf "{{inputs.parameters.config_status}}" }}' '{{ printf "{{inputs.parameters.reconcile_id}}" }}' '{{ printf "{{inputs.parameters.config_reconcile_id}}" }}'
      volumes:
        - name: tmp
          emptyDir: {}
      outputs:
        parameters:
          - name: reconcile_id
            valueFrom:
              path: /tmp/reconcile_id.txt
            globalName: reconcile_id
