apiVersion: stable.compuzest.com/v1
kind: Environment
metadata:
  name: zmart-checkout-dev
  namespace: zlifecycle
spec:
  teamName: checkout
  envName: dev
  components:
    - name: images
      type: terraform
      module:
        source: aws
        name: s3-bucket
      variables:
        - name: bucket
          value: "zmart-checkout-dev-images"
    - name: videos
      type: terraform
      dependsOn: [images]
      module:
        source: aws
        name: s3-bucket
      variables:
        - name: bucket
          value: "zmart-checkout-dev-videos"