# Copyright (C) 2020 CompuZest, Inc. - All Rights Reserved
#
# Unauthorized copying of this file, via any medium, is strictly prohibited
# Proprietary and confidential
#
# NOTICE: All information contained herein is, and remains the property of
# CompuZest, Inc. The intellectual and technical concepts contained herein are
# proprietary to CompuZest, Inc. and are protected by trade secret or copyright
# law. Dissemination of this information or reproduction of this material is
# strictly forbidden unless prior written permission is obtained from CompuZest, Inc.
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-trigger-template
  namespace: argocd
spec:
  entrypoint: run
  templates:
    - name: run
      inputs:
        parameters:
          - name: team_name
          - name: env_name
          - name: config_name
          - name: workflowtemplate
          - name: module_source
          - name: module_source_path
          - name: variables_file_source
          - name: variables_file_path
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: {{inputs.parameters.team_name}}-{{inputs.parameters.env_name}}-{{inputs.parameters.config_name}}
            namespace: argocd
            labels:
              terraform/sync: 'true'
          spec:
            arguments:
              parameters:
              - name: team_name
                value: {{inputs.parameters.team_name}}
              - name: env_name
                value: {{inputs.parameters.env_name}}
              - name: config_name
                value: {{inputs.parameters.config_name}}
              - name: module_source
                value: {{inputs.parameters.module_source}}
              - name: module_source_path
                value: {{inputs.parameters.module_source_path}}
              - name: variables_file_source
                value: {{inputs.parameters.variables_file_source}}
              - name: variables_file_path
                value: {{inputs.parameters.variables_file_path}}
            workflowTemplateRef:
              name: {{inputs.parameters.workflowtemplate}}
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
