apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-trigger-template
  namespace: argo
spec:
  entrypoint: run
  templates:
    - name: run
      inputs:
        parameters:
          - name: team_name
          - name: env_name
          - name: config_name
          - name: workflowtemplate
          - name: module_source
          - name: module_source_path
          - name: variables_file_source
          - name: variables_file_path
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: {{inputs.parameters.name}}
            namespace: argo
            labels:
              terraform/sync: 'true'
          spec:
            arguments:
              parameters:
              - name: team_name
                value: {{inputs.parameters.team_name}}
              - name: env_name
                value: {{inputs.parameters.env_name}}
              - name: config_name
                value: {{inputs.parameters.config_name}}
              - name: module_source
                value: {{inputs.parameters.module_source}}
              - name: module_source_path
                value: {{inputs.parameters.module_source_path}}
              - name: variables_file_source
                value: {{inputs.parameters.variables_file_source}}
              - name: variables_file_path
                value: {{inputs.parameters.variables_file_path}}
            workflowTemplateRef:
              name: {{inputs.parameters.workflowtemplate}}
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
