apiVersion: v1
kind: Service
metadata:
  name: {{ include "zlifecycle-event-service.fullname" . }}
  labels:
    {{- include "zlifecycle-event-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.streamPort }}
      targetPort: http2
      protocol: TCP
      name: http2
  selector:
    {{- include "zlifecycle-event-service.selectorLabels" . | nindent 4 }}
