---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: {{ .Values.corsAllowOrigin }}
spec:
  rules:
{{- range $path := .Values.argocd.paths }}
  - host: {{ $.Values.argocd.domain }}
    http:
      paths:
      - path: {{ . }}
        backend:
          serviceName: argocd-server
          servicePort: http
{{- end }}
  - host: {{ .Values.argocd.domain }}
    http:
      paths:
      - path: /api/v1/workflows
        backend:
          serviceName: argo-workflow-server
          servicePort: 2746
  - host: {{ .Values.argocd.domain }}
    http:
      paths:
      - path: /dex
        backend:
          serviceName: argocd-dex-server
          servicePort: http