---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  labels:
    kubernetes.io/ingress.class: alb
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: {{ .Values.corsAllowOrigin }}
spec:
  ingressClassName: nginx
  rules:
{{- range $path := .Values.argocd.paths }}
  - host: {{ $.Values.argocd.domain }}
    http:
      paths:
      - path: {{ . }}
        pathType: Prefix
        backend:
          service:
            name: argocd-{{ $.Values.company }}-server
            port:
              name: http
{{- end }}
  - host: {{ .Values.argocd.web_domain }}
    http:
      paths:
      - path: /api/dex
        pathType: Prefix
        backend:
          service:
            name: argocd-{{ .Values.company }}-server
            port:
              name: http
  - host: {{ .Values.argocd.domain }}
    http:
      paths:
      - path: /api/v1/workflows
        pathType: Prefix
        backend:
          service:
            name: argo-workflow-server
            port:
              number: 2746
