apiVersion: v1
kind: Secret
metadata:
 name: {{ .Values.operator.webhooks.tls.secretName }}
 annotations:
   reflector.v1.k8s.emberstack.com/reflects: "{{ .Values.operator.webhooks.tls.secretNamespace }}/{{ .Values.operator.webhooks.tls.secretName }}"
