apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: {{ .Values.company.config.name }}-system
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: controller-manager
