apiVersion: apps/v1
kind: Deployment
metadata:
  name: zlifecycle-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zlifecycle-api
  template:
    metadata:
     labels:
        app: zlifecycle-api
    spec:
      containers:
        - name: zlifecycle-api
          env:
            - name: ZL_ENVIRONMENT
              value: {{ .Values.zlEnvironment }}
            - name: TYPEORM_HOST
              value: {{ .Values.database.host }}
            - name: TYPEORM_DATABASE
              value: {{ .Values.database.name }}
            - name: TYPEORM_USERNAME
              value: {{ .Values.database.username }}
            - name: TYPEORM_PASSWORD
              value: {{ .Values.database.password }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.awsCredentials.accessKeyId}}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.awsCredentials.secretAccessKey}}
            - name: AWS_REGION
              value: {{ .Values.awsCredentials.region}}
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
