---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: audit-run-template
spec:
  entrypoint: run
  podGC:
    strategy: OnPodCompletion
  templates:
    - name: run-audit
      inputs:
        parameters:
          - name: customer_id
          - name: team_name
          - name: env_name
          - name: status
          - name: is_destroy
          - name: phase
          - name: reconcile_id
      serviceAccountName: {{.Values.serviceAccountName}}
      script:
        imagePullPolicy: IfNotPresent
        image: "413422438110.dkr.ecr.us-east-1.amazonaws.com/zlifecycle-terraform:{{.Values.terraformImageTag}}"
        command:
          - sh
        source: |
          ./audit.sh '{{ printf "{{inputs.parameters.team_name}}" }}' '{{ printf "{{inputs.parameters.env_name}}" }}' "0" '{{ printf "{{inputs.parameters.status}}" }}' "0" '{{ printf "{{inputs.parameters.reconcile_id}}" }}' "0" '{{ printf "{{inputs.parameters.is_destroy}}" }}' '{{ printf "{{inputs.parameters.phase}}" }}' "noSkip" '{{ printf "{{inputs.parameters.customer_id}}" }}'
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
          - name: ARGOCD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: argocd-creds
                key: ARGOCD_PASSWORD
        volumeMounts:
          - name: tmp
            mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      outputs:
        parameters:
          - name: reconcile_id
            valueFrom:
              path: /tmp/reconcile_id.txt
            globalName: reconcile_id
