apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notifications-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-notifications-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-notifications-controller
    spec:
      containers:
        - command:
            - /app/argocd-notifications
            - controller
          image: argoprojlabs/argocd-notifications:v0.6.0
          imagePullPolicy: Always
          name: argocd-notifications-controller
          workingDir: /app
      serviceAccountName: argocd-notifications-controller
