name: Main Branch Workflow
on:
  push:
    branches:
      - main

env:
  module_name: github.com/CompuZest/zlifecycle-api
jobs:
  build-test-push:
    name: Build, test, and push
    runs-on: ubuntu-20.04
    steps:
      # - uses: actions/setup-go@v1
      # - run: docker-compose -f docker-compose.test.yml build
      # - run: docker-compose -f docker-compose.test.yml up

      # Login to ECR
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - uses: actions/checkout@v2

      - run: docker build -t ${{ env.ECR_REPO }}/zlifecycle-api:latest .
        env:
          ECR_REPO: ${{ steps.login-ecr.outputs.registry }}
      - run: docker push ${{ env.ECR_REPO }}/zlifecycle-api:latest
        env:
          ECR_REPO: ${{ steps.login-ecr.outputs.registry }}

      - name: Send Slack Notfication
        uses: ravsamhq/notify-slack-action@master
        if: always()
        with:
          status: ${{ job.status }}
          notify_when: 'failure,warnings' # default is 'success,failure,warnings'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required