apiVersion: v1
kind: Secret
metadata:
  name: "zlifecycle-web-bff-development"
type: Opaque
data:
  OPENID_CLIENT_ID: {{ .Values.argocd.openIdClientId }}
  OPENID_CLIENT_SECRET: {{ .Values.argocd.openIdClientSecret }}