apiVersion: v1
kind: Service
metadata:
  name: zlifecycle-web-bff
spec:
  selector:
    app: zlifecycle-web-bff
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8080
  type: NodePort
