# The following manifests contain a self-signed issuer CR and a certificate CR.
# More document can be found at https://docs.cert-manager.io
# WARNING: Targets CertManager v1.0. Check https://cert-manager.io/docs/installation/upgrading/ for breaking changes.
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: {{ .Values.company.config.name }}-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert
  namespace: {{ .Values.company.config.name }}-system
spec:
  # $(SERVICE_NAME) and $(SERVICE_NAMESPACE) will be substituted by kustomize
  dnsNames:
    {{- range .Values.operator.webhooks.hosts }}
    - {{ . }}
    {{- end}}
    - webhook-service.{{ .Values.company.config.name }}-system.svc
    - webhook-service.{{ .Values.company.config.name }}-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: {{ .Values.operator.webhooks.tls.secretName }} # this secret will not be prefixed, since it's not managed by kustomize
