apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "core.fullname" . }}-controller-manager
  labels:
    {{- include "core.labels" . | indent 4 }}
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        {{- include "core.labels" . | indent 8 }}
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: manager
        env:
          - name: GITHUB_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-auth-token
                key: token
          {{- include "core.deployment.container-env" . | indent 10 }}
        envFrom:
          - configMapRef:
              name: company-config
          - secretRef:
              name: argocd-creds
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      terminationGracePeriodSeconds: 10
