apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "core.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "core.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "core.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
