apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zlifecycle-il-operator-manager-rolebinding
  namespace: {{ .Values.company.config.name }}-system
  labels:
    {{- include "core.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zlifecycle-il-operator-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.company.config.name }}-system
