apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
  namespace: zlifecycle-il-operator-system
  annotations:
    cert-manager.io/inject-ca-from: zlifecycle-il-operator-system/serving-cert
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: webhook-service
        namespace: zlifecycle-il-operator-system
        path: /validate-stable-compuzest-com-v1-environment
    failurePolicy: Fail
    name: venvironment.kb.io
    rules:
      - apiGroups:
          - stable.compuzest.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - environments
    sideEffects: None
    timeoutSeconds: 30
