apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zlifecycle-operator
  namespace: {{ .Values.company.config.name }}-system
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  rules:
    {{- $routes := .Values.operator.webhooks.routes }}
    {{- range $endpoint := .Values.operator.webhooks.hosts }}
    - host: {{ $endpoint }}
      http:
        paths:
          {{- range $route := $routes }}
          - path: {{ $route }}
            pathType: Prefix
            backend:
              service:
                name: webhook-service
                port:
                  number: 443
          {{- end }}
    {{- end }}
