image:
  name: zlifecycle-web-bff
  tag: latest
  repository:
replicas: 1
# rename zcustomer with the client name
domain:
company: !!!CompanyName!!!
ingressPaths:
  - "/auth"
  - "/cd"
  - "/wf"
  - "/authorize"
  - "/costing"
  - "/reconciliation"
  - "/secrets"
  - "/terraform"
  - "/terraform-external"
  - "/state"
  - "/company"
  - "/error-api"
  - "/events"
  - "/users"
  - "/session"
  - "/registration"
  - "/orgs"
  - "/public"
  - "/ops"
  - "/api"
  - "/ext"
protocol:
auth0:
  issuerBaseUrl:
  web:
    baseUrl:
    clientId:
    secret:
  api:
    clientId:
    secret:
    audience:
argocd:
  urlWithProtocol: http://argocd-server.argocd.svc.cluster.local
redis:
  url:
  password:
argoWorkflowApiUrl: http://argo-workflow-server.argocd.svc.cluster.local:2746
zlifecycleApiUrl: http://zlifecycle-api.zlifecycle-ui.svc.cluster.local
zlifecycleStateManagerUrl: http://zlifecycle-state-manager.zlifecycle-il-operator-system.svc.cluster.local
zlifecycleEventApiUrl: http://event-service.:org-system.svc.cluster.local
resources:
  requests:
    cpu: 300m
    memory: 450Mi
