version: '3.8'

services: 
  mysqldb:
    image: mysql:oracle
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nestjsrealworld
    ports:
      - "3306:3306"
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
      
volumes: 
  db-config:
  db-data:
