name: docs-gen
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - .github/workflows/docs-gen.yaml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-markdownextradata-plugin
      - run: mkdocs gh-deploy --force
