name: event-service - lint
on:
  push:
    tags:
      - v*
    branches-ignore:
      - master
      - main
    paths:
      - 'event-service/**'
      - .github/workflows/event-service-lint.yaml
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./event-service
    steps:
      - name: "Golang"
        uses: "actions/setup-go@v2"
        with:
          go-version: "1.18"
      - name: checkout
        uses: actions/checkout@v2
      - name: "Modules"
        run: "go mod download"
      - name: "Lint"
        uses: golangci/golangci-lint-action@v2
        with:
          version: "latest"
          skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true
          args: "-c ./.golangci.yaml --timeout=10m --issues-exit-code=0 --max-issues-per-linter=0 --sort-results ./..."
