name: il-operator - test
on:
  workflow_call:
  push:
    branches-ignore:
      - master
      - main
    paths:
      - 'il-operator/**'
      - .github/workflows/il-operator-test.yaml
permissions:
  contents: write
jobs:
  build:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: ./il-operator
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Golang"
        uses: "actions/setup-go@v2"
        with:
          go-version: "1.18"
      - id: go-cache-paths
        run: |
          echo "build=$(go env GOCACHE)" >>"$GITHUB_OUTPUT"
          echo "module=$(go env GOMODCACHE)" >>"$GITHUB_OUTPUT"
      # Cache go build cache, used to speedup go test
      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
      # Cache go mod cache, used to speedup builds
      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.module }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
      - name: "Test"
        run: go test -json ./controller/... > test.json
      - name: "Annotate"
        if: always()
        uses: guyarb/golang-test-annotations@v0.5.0
        with:
          test-results: test.json
