name: il-operator - lint
on:
  push:
    tags:
      - v*
    branches-ignore:
      - master
      - main
    paths:
      - 'il-operator/**'
      - .github/workflows/il-operator-lint.yaml
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: "Golang"
        uses: "actions/setup-go@v2"
        with:
          go-version: "1.18"
      - name: checkout
        uses: actions/checkout@v2
      - name: "Lint"
        uses: golangci/golangci-lint-action@v3
        with:
          version: "latest"
          args: "-c il-operator/.golangci.yml --timeout=10m --issues-exit-code=0 --max-issues-per-linter=0 --sort-results ./..."
