apiVersion: apps/v1
kind: Deployment
metadata:
  name: zlifecycle-api
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: zlifecycle-api
  template:
    metadata:
     labels:
        app: zlifecycle-api
    spec:
      serviceAccount: internal-api
      containers:
        - name: zlifecycle-api
          env:
            - name: CK_ENVIRONMENT
              value: {{ .Values.ckEnvironment }}
            - name: CK_ARGO_WF_URL
              value: {{ .Values.argowf.url }}
            - name: CK_ARGO_WF_NAMESPACE
              value: {{ .Values.argowf.namespace }}
            - name: CK_ARGO_WF_SKIP_PROVISION
              value: "false"
            - name: CK_ARGO_WF_ORG_URL
              value: {{ .Values.org.argowf.url }}
            - name: CK_ARGO_CD_URL
              value: {{ .Values.org.argocd.url }}
            - name: TYPEORM_HOST
              value: {{ .Values.database.host }}
            - name: TYPEORM_DATABASE
              value: {{ .Values.database.name }}
            - name: TYPEORM_USERNAME
              value: {{ .Values.database.username }}
            - name: TYPEORM_PASSWORD
              value: {{ .Values.database.password }}
            - name: TYPEORM_PORT
              value: "{{ .Values.database.port }}"
            - name: TYPEORM_SYNC
              value: "{{ .Values.database.sync }}"
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.awsCredentials.accessKeyId}}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.awsCredentials.secretAccessKey}}
            - name: AWS_SESSION_TOKEN
              value: {{ .Values.awsCredentials.sessionToken}}
            - name: AWS_REGION
              value: {{ .Values.awsCredentials.region}}
            - name: REDIS_URL
              value: {{ .Values.redis.url }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password }}
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
