apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-api
  namespace: {{.Values.namespace}}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-company
rules:
  - apiGroups: ["stable.cloudknit.io"]
    resources: ["companies"]
    verbs: ["patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: internal-api
subjects:
  - kind: ServiceAccount
    name: internal-api
    namespace: {{.Values.namespace}}
roleRef:
  kind: ClusterRole
  name: patch-company
  apiGroup: rbac.authorization.k8s.io
