apiVersion: v1
kind: Service
metadata:
  name: zlifecycle-api
spec:
  selector:
    app: zlifecycle-api
  ports:
    - name: http
      port: 80
      targetPort: 3000
    - name: https
      port: 443
      targetPort: 3000
  type: NodePort
