name: Master Branch Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  module_name: github.com/CompuZest/zlifecycle-state-manager  # from go.mod
jobs:
  build-test-push:
    name: Build, test, and push
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '^1.15.8'  # should match Dockerfile and go.mod

      - run: go version
      - run: echo "GOPATH=${GITHUB_WORKSPACE}/go" >> $GITHUB_ENV
      - run: echo "${{ env.GOPATH }}/bin" >> $GITHUB_PATH
      - run: go env

      - uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/${{ env.module_name }}

      # Login to ECR
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - run: make deps
        working-directory: ${{ env.GOPATH }}/src/${{ env.module_name }}
      - run: go mod vendor
        working-directory: ${{ env.GOPATH }}/src/${{ env.module_name }}
      - run: make check
        working-directory: ${{ env.GOPATH }}/src/${{ env.module_name }}
      - run: make docker-build
        if: github.ref == 'refs/heads/main'
        working-directory: ${{ env.GOPATH }}/src/${{ env.module_name }}
      - run: make docker-push
        if: github.ref == 'refs/heads/main'
        working-directory: ${{ env.GOPATH }}/src/${{ env.module_name }}
        env:
          ECR_REPO: ${{ steps.login-ecr.outputs.registry }}

      - name: Send Slack Notfication
        uses: ravsamhq/notify-slack-action@master
        if: always()
        with:
          status: ${{ job.status }}
          notify_when: 'failure,warnings' # default is 'success,failure,warnings'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
